/* Generated by umd builder */
<% if (!root.unit) { %>window.appConfig || (window.appConfig = {});<% } %>
(function() {
    'use strict';
    var config = <%= root.config %>;
    <% if (!root.unit) { %>
    if (!/\\.\\w+$/.test(window.location.pathname)) {
        if (typeof appConfig.baseUrl === 'string') {
            config.baseUrl = appConfig.baseUrl + config.baseUrl;
        } else {
            config.baseUrl = '/' + config.baseUrl;
        }
    }
    <% } %>
    var deps = config.deps;
    delete config.deps;

    var bundles = <%= root.bundles %>,
        component;
    for (component in bundles) {
        define(component, bundles[component], function(main) {
            return main;
        });
    }
    requirejs.config(config);
    <% if (root.unit) { %>
        require(['<%= root.loader %>', '<%= root.pathBrowserify %>'], function(depsLoader, pathBrowserify) {
            window.depsLoader = depsLoader;

            var allTestFiles = [];
            var TEST_REGEXP = /\btest\.js$/;

            // add test files
            Object.keys(window.__karma__.files).forEach(function(file) {
                if (TEST_REGEXP.test(file)) {
                    deps.push(pathToModule(file));
                }
            });

            // We have to kickoff testing framework,
            // after RequireJS is done with loading all the files.
            require(deps, window.__karma__.start);

            // Normalize a path to RequireJS module name.
            function pathToModule(path) {
                return pathBrowserify.relative(config.baseUrl, path).replace(/\.js$/, '');
            }
        });
    <% } else { %>
        define(['<%= root.loader %>'], function(depsLoader) {
            window.depsLoader = depsLoader;
            require(deps, function() {
                require(['initialize']);
            });
        });
    <% } %>
})();