'use strict';
var _, generateConfig, log4js, logger, sysPath;

log4js = require('../log4js');

logger = log4js.getLogger('umd-builder');

_ = require('lodash');

_.template = require('./compilers/jst/template');

_.templateSettings.variable = 'root';

_.templateSettings.ignore = /<%--([\s\S]+?)--%>/g;

sysPath = require('path');

exports.generateConfig = generateConfig = function(options) {
  var APPLICATION_PATH, BOWER_COMPONENTS_ABSOLUTE_PATH, BOWER_COMPONENTS_RELATIVE_PATH, BOWER_COMPONENTS_URL, BOWER_PUBLIC_PATH, CLIENT_ASSETS_PATH, CLIENT_ASSETS_RELATIVE_PATH, CLIENT_MODULES_PATH, CLIENT_MODULES_URL, CLIENT_PATH, CLIENT_RELATIVE_PATH, PUBLIC_PATH, config;
  config = {};
  APPLICATION_PATH = sysPath.resolve(options.paths.root);
  CLIENT_RELATIVE_PATH = options.paths.watched[0];
  CLIENT_PATH = sysPath.join(APPLICATION_PATH, CLIENT_RELATIVE_PATH);
  CLIENT_ASSETS_PATH = sysPath.join(CLIENT_PATH, 'assets');
  CLIENT_ASSETS_RELATIVE_PATH = sysPath.relative(CLIENT_PATH, CLIENT_ASSETS_PATH);
  BOWER_COMPONENTS_RELATIVE_PATH = 'bower_components';
  PUBLIC_PATH = sysPath.resolve(APPLICATION_PATH, options.paths["public"]);
  CLIENT_MODULES_URL = options.paths.modules || 'node_modules';
  CLIENT_MODULES_PATH = sysPath.join(PUBLIC_PATH, CLIENT_MODULES_URL);
  BOWER_PUBLIC_PATH = sysPath.join(PUBLIC_PATH, BOWER_COMPONENTS_RELATIVE_PATH);
  BOWER_COMPONENTS_ABSOLUTE_PATH = sysPath.join(APPLICATION_PATH, BOWER_COMPONENTS_RELATIVE_PATH);
  BOWER_COMPONENTS_URL = sysPath.relative(CLIENT_MODULES_PATH, BOWER_PUBLIC_PATH).replace(/[\\]/g, '/');
  config.paths = {
    APPLICATION_PATH: APPLICATION_PATH,
    CLIENT_RELATIVE_PATH: CLIENT_RELATIVE_PATH,
    CLIENT_PATH: CLIENT_PATH,
    CLIENT_ASSETS_PATH: CLIENT_ASSETS_PATH,
    CLIENT_ASSETS_RELATIVE_PATH: CLIENT_ASSETS_RELATIVE_PATH,
    BOWER_COMPONENTS_ABSOLUTE_PATH: BOWER_COMPONENTS_ABSOLUTE_PATH,
    BOWER_COMPONENTS_RELATIVE_PATH: BOWER_COMPONENTS_RELATIVE_PATH,
    PUBLIC_PATH: PUBLIC_PATH,
    CLIENT_MODULES_URL: CLIENT_MODULES_URL,
    CLIENT_MODULES_PATH: CLIENT_MODULES_PATH,
    BOWER_PUBLIC_PATH: BOWER_PUBLIC_PATH,
    BOWER_COMPONENTS_URL: BOWER_COMPONENTS_URL
  };
  return config;
};
