// Generated by CoffeeScript 1.10.0
var JstCompiler, _, sysPath;

sysPath = require('path');

_ = require('lodash');

_.template = require('./template');

module.exports = JstCompiler = (function() {
  JstCompiler.prototype.brunchPlugin = true;

  JstCompiler.prototype.type = 'template';

  JstCompiler.prototype.extension = 'jst';

  function JstCompiler(config) {
    if (config == null) {
      config = {};
    }
    this.nameCleaner = config.modules.nameCleaner || function(path) {
      return path;
    };
    this.options = config.plugins && config.plugins.jst;
  }

  JstCompiler.prototype.compile = function(params, next) {
    var data, e, error, map, options, path, template;
    data = params.data, path = params.path, map = params.map;
    try {
      options = _.extend({}, this.options, {
        sourceURL: this.nameCleaner(path)
      });
      template = _.template(data, options).source;
      data = "function factory(require) {\n    'use strict';\n    return " + template + ";\n}";
      next(null, {
        data: data,
        path: path,
        map: map
      });
    } catch (error) {
      e = error;
      next(e, {
        data: data,
        path: path,
        map: map
      });
    }
  };

  return JstCompiler;

})();
